// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using newWebAPI.Models;

#nullable disable

namespace newWebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231207103958_FilmCreateDeux")]
    partial class FilmCreateDeux
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("newWebAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Autor = "Christian Nagel",
                            CreatedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1194),
                            CreatedBy = "",
                            DeletedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1243),
                            Description = "A true masterclass in C# and .NET programming",
                            Genre = "Software",
                            Price = 50m,
                            PublishDate = new DateTime(2016, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Professional C# 6 and .NET Core 1.0",
                            UpdatedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1241),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 2,
                            Autor = "Christian Nagel",
                            CreatedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1256),
                            CreatedBy = "",
                            DeletedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1260),
                            Description = "A true masterclass in C# and .NET programming",
                            Genre = "Software",
                            Price = 50m,
                            PublishDate = new DateTime(2018, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Professional C# 7 and .NET Core 2.0",
                            UpdatedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1258),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 3,
                            Autor = "Christian Nagel",
                            CreatedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1265),
                            CreatedBy = "",
                            DeletedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1269),
                            Description = "A true masterclass in C# and .NET programming",
                            Genre = "Software",
                            Price = 50m,
                            PublishDate = new DateTime(2019, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Professional C# 8 and .NET Core 3.0",
                            UpdatedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1267),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 4,
                            Autor = "Christian Nagel",
                            CreatedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1273),
                            CreatedBy = "",
                            DeletedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1276),
                            Description = "A true masterclass in C# and .NET programming",
                            Genre = "Software",
                            Price = 50m,
                            PublishDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Professional C# 9 and .NET 5",
                            UpdatedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1274),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 5,
                            Autor = "Perkins, Reid, and Hammer",
                            CreatedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1279),
                            CreatedBy = "",
                            DeletedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1282),
                            Description = "The perfect guide to Visual C#",
                            Genre = "Software",
                            Price = 45m,
                            PublishDate = new DateTime(2020, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Beginning Visual C# 2019",
                            UpdatedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1281),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 6,
                            Autor = "Andrew Troelsen",
                            CreatedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1285),
                            CreatedBy = "",
                            DeletedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1289),
                            Description = "The ultimate C# resource",
                            Genre = "Software",
                            Price = 50m,
                            PublishDate = new DateTime(2017, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pro C# 7",
                            UpdatedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1287),
                            UpdatedBy = ""
                        });
                });

            modelBuilder.Entity("newWebAPI.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Commande")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Duree")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Autor = "MonPremierAuteur",
                            Commande = 20,
                            CreatedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1463),
                            CreatedBy = "",
                            DeletedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1467),
                            Description = "Pas mal",
                            Duree = new DateTime(2017, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Animé",
                            Price = 15m,
                            PublishDate = new DateTime(2017, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 3,
                            Title = "Mon Premier Film",
                            UpdatedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1466),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 2,
                            Autor = "MonDeuxiemeAuteur",
                            Commande = 5,
                            CreatedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1476),
                            CreatedBy = "",
                            DeletedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1479),
                            Description = "Tres bien",
                            Duree = new DateTime(2014, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Animé",
                            Price = 15m,
                            PublishDate = new DateTime(2012, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 1,
                            Title = "Mon Deuxieme Film",
                            UpdatedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1477),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 3,
                            Autor = "MonTroisiemeAuteur",
                            Commande = 28,
                            CreatedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1484),
                            CreatedBy = "",
                            DeletedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1487),
                            Description = "OK",
                            Duree = new DateTime(2017, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Action",
                            Price = 35m,
                            PublishDate = new DateTime(2017, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 9,
                            Title = "Mon Troisieme Film",
                            UpdatedAt = new DateTime(2023, 12, 7, 11, 39, 57, 760, DateTimeKind.Local).AddTicks(1485),
                            UpdatedBy = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
