// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using newWebAPI.Models;

#nullable disable

namespace newWebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231206114520_Test")]
    partial class Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("newWebAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Autor = "Christian Nagel",
                            CreatedAt = new DateTime(2023, 12, 6, 12, 45, 20, 202, DateTimeKind.Local).AddTicks(6211),
                            CreatedBy = "",
                            DeletedAt = new DateTime(2023, 12, 6, 12, 45, 20, 202, DateTimeKind.Local).AddTicks(6264),
                            Description = "A true masterclass in C# and .NET programming",
                            Genre = "Software",
                            Price = 50m,
                            PublishDate = new DateTime(2016, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Professional C# 6 and .NET Core 1.0",
                            UpdatedAt = new DateTime(2023, 12, 6, 12, 45, 20, 202, DateTimeKind.Local).AddTicks(6262),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 2,
                            Autor = "Christian Nagel",
                            CreatedAt = new DateTime(2023, 12, 6, 12, 45, 20, 202, DateTimeKind.Local).AddTicks(6277),
                            CreatedBy = "",
                            DeletedAt = new DateTime(2023, 12, 6, 12, 45, 20, 202, DateTimeKind.Local).AddTicks(6280),
                            Description = "A true masterclass in C# and .NET programming",
                            Genre = "Software",
                            Price = 50m,
                            PublishDate = new DateTime(2018, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Professional C# 7 and .NET Core 2.0",
                            UpdatedAt = new DateTime(2023, 12, 6, 12, 45, 20, 202, DateTimeKind.Local).AddTicks(6278),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 3,
                            Autor = "Christian Nagel",
                            CreatedAt = new DateTime(2023, 12, 6, 12, 45, 20, 202, DateTimeKind.Local).AddTicks(6284),
                            CreatedBy = "",
                            DeletedAt = new DateTime(2023, 12, 6, 12, 45, 20, 202, DateTimeKind.Local).AddTicks(6287),
                            Description = "A true masterclass in C# and .NET programming",
                            Genre = "Software",
                            Price = 50m,
                            PublishDate = new DateTime(2019, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Professional C# 8 and .NET Core 3.0",
                            UpdatedAt = new DateTime(2023, 12, 6, 12, 45, 20, 202, DateTimeKind.Local).AddTicks(6286),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 4,
                            Autor = "Christian Nagel",
                            CreatedAt = new DateTime(2023, 12, 6, 12, 45, 20, 202, DateTimeKind.Local).AddTicks(6290),
                            CreatedBy = "",
                            DeletedAt = new DateTime(2023, 12, 6, 12, 45, 20, 202, DateTimeKind.Local).AddTicks(6293),
                            Description = "A true masterclass in C# and .NET programming",
                            Genre = "Software",
                            Price = 50m,
                            PublishDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Professional C# 9 and .NET 5",
                            UpdatedAt = new DateTime(2023, 12, 6, 12, 45, 20, 202, DateTimeKind.Local).AddTicks(6292),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 5,
                            Autor = "Perkins, Reid, and Hammer",
                            CreatedAt = new DateTime(2023, 12, 6, 12, 45, 20, 202, DateTimeKind.Local).AddTicks(6297),
                            CreatedBy = "",
                            DeletedAt = new DateTime(2023, 12, 6, 12, 45, 20, 202, DateTimeKind.Local).AddTicks(6300),
                            Description = "The perfect guide to Visual C#",
                            Genre = "Software",
                            Price = 45m,
                            PublishDate = new DateTime(2020, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Beginning Visual C# 2019",
                            UpdatedAt = new DateTime(2023, 12, 6, 12, 45, 20, 202, DateTimeKind.Local).AddTicks(6298),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 6,
                            Autor = "Andrew Troelsen",
                            CreatedAt = new DateTime(2023, 12, 6, 12, 45, 20, 202, DateTimeKind.Local).AddTicks(6303),
                            CreatedBy = "",
                            DeletedAt = new DateTime(2023, 12, 6, 12, 45, 20, 202, DateTimeKind.Local).AddTicks(6306),
                            Description = "The ultimate C# resource",
                            Genre = "Software",
                            Price = 50m,
                            PublishDate = new DateTime(2017, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pro C# 7",
                            UpdatedAt = new DateTime(2023, 12, 6, 12, 45, 20, 202, DateTimeKind.Local).AddTicks(6305),
                            UpdatedBy = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
